---
- name: restart zabbix-agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted

- name: restart wazuh-agent
  ansible.builtin.systemd:
    name: wazuh-agent
    state: restarted

- name: restart glpi-agent
  ansible.builtin.systemd:
    name: glpi-agent
    state: restarted
