ansible_host: "{{ inventory_hostname }}.pymesis.lab"
ansible_user: "PYMESIS\\Administrator"
ansible_password: "{{ vault_windows_admin_password }}"
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: validate
ansible_winrm_ca_trust_path: /usr/local/share/ca-certificates/pymesis-ca.crt
ansible_port: 5986
ansible_become: false
